# SPDX-FileCopyrightText: 2025 wahl.chat
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

"""Implementation of topic combiner agent."""

import logging
from collections import defaultdict
from datetime import datetime, timezone

from langchain_core.messages import HumanMessage, SystemMessage

from src.guided_exploration.agents.base import BaseAgent
from src.guided_exploration.agents.llm_provider import LLMProvider
from src.guided_exploration.agents.topic_combiner.interface import (
    TopicCombinerInput,
    TopicCombinerOutput,
)
from src.guided_exploration.agents.party_context import format_party_context_for_prompt
from src.guided_exploration.agents.topic_combiner.prompts import (
    COMBINING_PROMPT,
    SYSTEM_PROMPT,
    TopicCombinerLLMOutput,
    format_party_trees,
)
from src.guided_exploration.models.tree import Subtopic, Topic, TopicTree

logger = logging.getLogger(__name__)


class TopicCombinerAgent(BaseAgent[TopicCombinerInput, TopicCombinerOutput]):
    """
    Combines multiple party topic trees into a unified exploration tree.

    Takes topic trees from each party (generated by PartyTopicResolverAgent)
    and merges them into a single coherent structure that:
    - Includes all relevant topics from all parties
    - Merges similar topics across parties
    - Tracks which parties cover which subtopics
    - Creates a neutral, party-agnostic navigation structure
    """

    def __init__(self, llm_provider: LLMProvider):
        self._llm = llm_provider

    @property
    def name(self) -> str:
        return "topic_combiner"

    async def execute(self, input: TopicCombinerInput) -> TopicCombinerOutput:
        """
        Combine party topic trees into unified exploration tree using LLM.

        Uses semantic understanding to merge conceptually similar topics
        across parties into a neutral, unified structure.
        """
        # Format party trees and context for the prompt
        formatted_trees = format_party_trees(input.party_trees, input.parties)
        party_context = format_party_context_for_prompt(
            parties=input.parties,
            context_name=input.context_name,
        )

        # Build system prompt with context
        system_prompt = SYSTEM_PROMPT.format(
            context_name=input.context_name,
            party_context=party_context,
        )

        # Build messages
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(
                content=COMBINING_PROMPT.format(
                    query=input.query,
                    party_trees=formatted_trees,
                )
            ),
        ]

        # Use structured output for reliable parsing
        llm_output: TopicCombinerLLMOutput = await self._llm.generate_structured(
            messages=messages,
            output_schema=TopicCombinerLLMOutput,
            temperature=0.3,  # Slightly creative for semantic merging
        )

        # Convert LLM output to domain models and build party coverage
        topics, party_coverage = self._convert_to_unified_tree(llm_output)

        topic_tree = TopicTree(
            exploration_id="",  # Will be set by orchestrator
            original_query=input.query,
            topics=topics,
            created_at=datetime.now(timezone.utc),
            updated_at=datetime.now(timezone.utc),
        )

        return TopicCombinerOutput(
            topic_tree=topic_tree,
            party_coverage=party_coverage,
        )

    def _convert_to_unified_tree(
        self,
        llm_output: TopicCombinerLLMOutput,
    ) -> tuple[list[Topic], dict[str, list[str]]]:
        """Convert LLM output to Topic domain models and party coverage."""
        topics = []
        party_coverage: dict[str, list[str]] = defaultdict(list)

        for llm_topic in llm_output.topics:
            subtopics = []

            for llm_subtopic in llm_topic.subtopics:
                subtopic_id = f"{llm_topic.id}.{llm_subtopic.id}"

                # Track party coverage
                party_coverage[subtopic_id] = llm_subtopic.source_parties

                subtopics.append(
                    Subtopic(
                        id=subtopic_id,
                        name=llm_subtopic.name,
                        description=llm_subtopic.description,
                        scope=llm_subtopic.scope,
                        parties=llm_subtopic.source_parties,
                        status="pending",
                    )
                )

            topics.append(
                Topic(
                    id=llm_topic.id,
                    name=llm_topic.name,
                    description=llm_topic.description,
                    subtopics=subtopics,
                    status="pending",
                )
            )

        return topics, dict(party_coverage)
