"""Quiz models for knowledge retention measurement."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class QuizStatus(str, Enum):
    """Status of quiz generation."""

    PENDING = "pending"
    GENERATING = "generating"
    READY = "ready"
    FAILED = "failed"


class QuizQuestion(BaseModel):
    """A single multiple-choice quiz question.

    Options 0-3 are content choices generated by the LLM. Option 4 is
    always ``"Weiß ich nicht"``, appended during conversion from the
    generator output. ``correct_index`` is always 0-3 — don't-know is
    never the correct answer, only a valid response.
    """

    id: str = Field(..., description="Unique question identifier")
    question: str = Field(..., description="The question text")
    options: list[str] = Field(
        ...,
        description="Answer options (4 content + 1 'Weiß ich nicht')",
        min_length=5,
        max_length=5,
    )
    correct_index: int = Field(
        ...,
        description="Index of the correct answer (0-3); never 4 (don't-know)",
        ge=0,
        le=3,
    )
    party: str | None = Field(
        default=None,
        description=(
            "For Type B/C questions: the party the question is about. "
            "For Type A ('Welche Partei …?'): null, since the party is the answer."
        ),
    )
    topic: str = Field(..., description="The topic this question covers")
    source_excerpt: str | None = Field(
        default=None,
        description="Excerpt from chat that this question is based on",
    )


class QuizAnswer(BaseModel):
    """A participant's answer to a quiz question.

    ``selected_index`` 0-3 are content choices; 4 is "Weiß ich nicht".
    """

    question_id: str = Field(..., description="ID of the question being answered")
    selected_index: int = Field(
        ...,
        description="Index of the selected answer (0-4; 4 = don't-know)",
        ge=0,
        le=4,
    )
    is_correct: bool = Field(..., description="Whether the answer was correct")
    response_time_ms: int | None = Field(
        default=None,
        description="Time taken to answer in milliseconds",
    )


class Quiz(BaseModel):
    """A complete quiz generated for a task."""

    id: str = Field(..., description="Unique quiz identifier")
    session_id: str = Field(..., description="The session this quiz belongs to")
    status: QuizStatus = Field(
        default=QuizStatus.PENDING,
        description="Current status of quiz generation",
    )
    questions: list[QuizQuestion] = Field(
        default_factory=list,
        description="The quiz questions",
    )
    created_at: datetime = Field(..., description="When the quiz was created")
    generated_at: datetime | None = Field(
        default=None,
        description="When the quiz finished generating",
    )
    error_message: str | None = Field(
        default=None,
        description="Error message if generation failed",
    )

    class Config:
        """Pydantic configuration."""

        use_enum_values = True


class QuizSubmission(BaseModel):
    """A participant's submission for a quiz."""

    quiz_id: str = Field(..., description="ID of the quiz being submitted")
    answers: list[QuizAnswer] = Field(..., description="The participant's answers")
    submitted_at: datetime = Field(..., description="When the quiz was submitted")
    total_correct: int = Field(..., description="Number of correct answers")
    total_questions: int = Field(..., description="Total number of questions")
    score_percentage: float = Field(..., description="Score as a percentage (0-100)")


def calculate_quiz_score(
    questions: list[QuizQuestion],
    answers: list[QuizAnswer],
) -> tuple[int, int, float]:
    """
    Calculate quiz score from questions and answers.

    Returns:
        Tuple of (correct_count, total_count, percentage)
    """
    if not questions:
        return 0, 0, 0.0

    question_map = {q.id: q for q in questions}
    correct = sum(
        1
        for a in answers
        if a.question_id in question_map
        and a.selected_index == question_map[a.question_id].correct_index
    )
    total = len(questions)
    percentage = (correct / total) * 100 if total > 0 else 0.0

    return correct, total, percentage
